name: PR

on:
  pull_request:

  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ^15.6

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node dependencies
        run: |
          npm install --global pnpm
          pnpm install

      - name: Build
        run: |
          pnpm run --recursive build

      - name: Run linter
        run: |
          pnpm run --recursive lint

      - name: Tests
        env:
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        run: |
          pnpm run --recursive test
