name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  release:
    name: Build and release packages
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ^15.2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node dependencies
        run: |
          npm install --global pnpm
          pnpm install

      - name: Run linter
        run: |
          pnpm run --recursive lint

      # TODO(durandj): run tests

      - name: Create release
        run: |
          pnpm run publish
